#For the tokens, do not put in quotes or else it won't work
[Authentication]
Discord Token = 

[Toggles]
Corruption = False
Jester = False
Rin = False
Glitched = True
Dreamspace = True
Cyberspace = True

[Technical]
Use LDPlayer = False
LDPlayer Path = C:\LDPlayer\LDPlayer9

[Webhook]
Discord User ID =
Webhook Link = 